spring:
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    hostname: discovery-eureka
#    ip-address: 182.254.192.61
#    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/