spring:
  application:
    name: discovery
#server:
#  port: 8080
eureka:
  instance:
    hostname: localhost
    ip-address: 182.254.192.61
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/